# Generated by Django 3.2.7 on 2021-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_creatures_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nichego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='creatures',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
